<?php
//http://pplware.sapo.pt/tutoriais/programacao-web-e-a-quinta-feira/
return [
	'Aveiro' => array('Águeda','Albergaria-a-Velha','Anadia','Arouca','Aveiro','Castelo de Paiva','Espinho','Estarreja','Santa Maria da Feira','Ílhavo','Mealhad','Murtosa','Oliveira de Azeméis','Oliveira do Bairro','Ovar','São João da Madeira','Sever do Vouga','Vagos','Vale de Cambra'),
	'Beja' => array('Aljustrel','Almodôvar','Alvito','Barrancos','Beja','Castro Verde','Cuba','Ferreira do Alentejo','Mértola','Moura','Odemira','Ourique','Serpa','Vidigueira'),
	'Braga' => array('Amares','Barcelos','Braga','Cabeceiras de Basto','Celorico de Basto','Esposende','Fafe','Guimarães','Póvoa de Lanhoso','Terras de Bouro','Vieira do Minho','Vila Nova de Famalicão','Vila Verde','Vizela'),
	'Bragança' => array('Alfandega da Fé','Bragança','Carrazeda de Ansiães','Freixo Espada à Cinta','Macedo de Cavaleiros','Miranda do Douro','Mirandela','Mogadouro','Torre de Moncorvo','Vila Flor','Vimioso','Vinhais'),
	'Castelo Branco' => array('Belmonte','Castelo Branco','Covilhã','Fundão','Idanha-a-Nova','Oleiros','Penamacor','Proença-a-Nova','Sertã','Vila de Rei','Vila Velha de Rodão'),
	'Coimbra' => array('Arganil','Cantanhede','Coimbra','Condeixa-a-Nova','Figueira da Foz','Góis','Lousã','Mira','Miranda do Corvo','Montemor-o-Velho','Oliveira do Hospital','Pampilhosa da Serra','Penacova','Penela','Soure','Tábua','Vila Nova de Poiares'),
	'Évora' => array('Alandroal','Arraiolos','Borba','Estremoz','Évora','Montemor-o-Novo','Mora','Mourão','Portel','Redondo','Reguengos de Monsaraz','Vendas Novas','Viana do Alentejo','Vila Viçosa'),
	'Faro' => array('Albufeira','Alcoutim','Aljezur','Castro Marim','Faro','Lagoa (Algarve)','Lagos','Loulé','Monchique','Olhão','Portimão','São Brás de Alportel','Silves','Tavira','Vila do Bispo','Vila Real de Santo António'),
	'Guarda' => array('Aguiar da Beira','Almeida','Celorico da Beira','Figueira de Castelo Rodrigo','Fornos de Algodres','Gouveia','Guarda','Manteigas','Meda','Pinhel','Sabugal','Seia','Trancoso','Vila Nova de Foz Côa'),
	'Leiria' => array('Alcobaça','Alvaiázere','Ansião','Batalha','Bombarral','Caldas da Rainha','Castanheira de Pêra','Figueiró dos Vinhos','Leiria','Marinha Grande','Nazaré','Óbidos','Pedrógão Grande','Peniche','Pombal','Porto de Mós','Alenquer'),
	'Lisboa' => array('Arruda dos Vinhos','Azambuja','Cadaval','Cascais','Lisboa','Loures','Lourinhã','Mafra','Oeiras','Sintra','Sobral de Monte Agraço','Torres Vedras','Vila Franca de Xira','Amadora','Odivelas'),
	'Portalegre' => array('Alter do Chão','Arronches','Avis','Campo Maior','Castelo de Vide','Crato','Elvas','Fronteira','Gavião','Marvão','Monforte','Nisa','Ponte de Sor','Portalegre','Sousel'),
	'Porto' => array('Amarante','Baião','Felgueiras','Gondomar','Lousada','Maia','Marco de Canaveses','Matosinhos','Paços de Ferreira','Paredes','Penafiel','Porto','Póvoa de Varzim','Santo Tirso','Valongo','Vila do Conde','Vila Nova de Gaia','Trofa'),
	'Santarém' => array('Abrantes','Alcanena','Almeirim','Alpiarça','Benavente','Cartaxo','Chamusca','Constância','Coruche','Entroncamento','Ferreira do Zêzere','Golegã','Mação','Rio Maior','Salvaterra de Magos','Santarém','Sardoal','Tomar','Torres Novas','Vila Nova da Barquinha','Ourém15','Alcácer do Sal'),
	'Setúbal' => array('Alcochete','Almada','Barreiro','Grândola','Moita','Montijo','Palmela','Santiago do Cacém','Seixal','Sesimbra','Setúbal','Sines'),
	'Viana do Castelo' => array('Arcos de Valdevez','Caminha','Melgaço','Monção','Paredes de Coura','Ponte da Barca','Ponte de Lima','Valença','Viana do Castelo','Vila Nova de Cerveira'),
	'Vila Real' => array('Alijó','Boticas','Chaves','Mesão Frio','Mondim de Basto','Montalegre','Murça','Peso da Régua','Ribeira de Pena','Sabrosa','Santa Marta de Penaguião','Valpaços','Vila Pouca de Aguiar','Vila Real'),
	'Viseu' => array('Armamar','Carregal do Sal','Castro Daire','Cinfães','Lamego','Mangualde','Moimenta da Beira','Mortágua','Nelas','Oliveira de Frades','Penalva do Castelo','Penedono','Resende','Santa Comba Dão','São João da Pesqueira','São Pedro do Sul','Sátão','Sernancelhe','Tabuaço','Tarouca','Tondela','Vila Nova de Paiva','Viseu','Vouzela'),
	'Ilha da Madeira' => array('Calheta (Madeira)','Câmara de Lobos','Funchal','Machico','Ponta do Sol','Porto Moniz','Ribeira Brava','Santa Cruz','Santana','São Vicente'),
	'Ilha de Porto Santo' => array('Porto Santo'),
	'Ilha de Santa Maria' => array('Vila do Porto'),
	'Ilha de São Miguel' => array('Lagoa (São Miguel)','Nordeste','Ponta Delgada','Povoação','Ribeira Grande','Vila Franca do Campo'),
	'Ilha Terceira' => array('Angra do Heroísmo','Praia da Vitória'),
	'Ilha da Graciosa' => array('Santa Cruz da Graciosa'),
	'Ilha de São Jorge' => array('Calheta (São Jorge)','Velas'),
	'Ilha do Pico' => array('Lajes do Pico','Madalena','São Roque do Pico'),
	'Ilha do Faial' => array('Horta'),
	'Ilha das Flores' => array('Lajes das Flores','Santa Cruz das Flores'),
	'Ilha do Corvo' => array('Corvo'),
];
